Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:



In [2]:
import numpy as np

In [3]:
arr=np.array([2,3,4,5,6])

a) Addition of 2 in all the element

In [4]:
print(arr+2)

[4 5 6 7 8]


b) Multiply 3 with all the elements

In [5]:
print(arr*3)

[ 6  9 12 15 18]


c) Divide every element by 2

In [6]:
print(arr/2)

[1.  1.5 2.  2.5 3. ]


Q.2 Questions on Basic NumPy Array:


a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [7]:
arr_2=np.array([1,2,3,6,4,5])
reverse_arr = arr_2[::-1]
print(reverse_arr)

[5 4 6 3 2 1]


b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])


In [8]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
unique, counts = np.unique(x, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]
indices = np.where(x== most_frequent_value)[0]

most_frequent_value, indices

(1, array([0, 5, 7, 8, 9], dtype=int64))

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [9]:


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# Find the most frequent value and their indices
unique, counts = np.unique(y, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]
indices = np.where(y == most_frequent_value)[0]

most_frequent_value, indices

(1, array([0, 1, 2], dtype=int64))

Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [10]:
arr_3=np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

In [11]:
print(arr_3[0][1])   ###acess 1st row and 2 nd column
print(arr_3[2][0])    ## acess 3rd row and 1st column

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [12]:
Ayush_arr=np.linspace(10,100,25)
print(f"DIMENSIONS :{Ayush_arr.ndim}")
print(f"SHAPE :{Ayush_arr.shape}")
print(f"TOTAL ELEMENTS :{Ayush_arr.size}")
for i in Ayush_arr:
  print(f"Data_type of {i} : {type(i)}")


DIMENSIONS :1
SHAPE :(25,)
TOTAL ELEMENTS :25
Data_type of 10.0 : <class 'numpy.float64'>
Data_type of 13.75 : <class 'numpy.float64'>
Data_type of 17.5 : <class 'numpy.float64'>
Data_type of 21.25 : <class 'numpy.float64'>
Data_type of 25.0 : <class 'numpy.float64'>
Data_type of 28.75 : <class 'numpy.float64'>
Data_type of 32.5 : <class 'numpy.float64'>
Data_type of 36.25 : <class 'numpy.float64'>
Data_type of 40.0 : <class 'numpy.float64'>
Data_type of 43.75 : <class 'numpy.float64'>
Data_type of 47.5 : <class 'numpy.float64'>
Data_type of 51.25 : <class 'numpy.float64'>
Data_type of 55.0 : <class 'numpy.float64'>
Data_type of 58.75 : <class 'numpy.float64'>
Data_type of 62.5 : <class 'numpy.float64'>
Data_type of 66.25 : <class 'numpy.float64'>
Data_type of 70.0 : <class 'numpy.float64'>
Data_type of 73.75 : <class 'numpy.float64'>
Data_type of 77.5 : <class 'numpy.float64'>
Data_type of 81.25 : <class 'numpy.float64'>
Data_type of 85.0 : <class 'numpy.float64'>
Data_type of 88.75 :

In [13]:
print(f"total number of bytes comsumed :{Ayush_arr.nbytes}")

total number of bytes comsumed :200


In [14]:
print(Ayush_arr.reshape(25))   ## yes we can make transpaose using reshape function also
print(Ayush_arr.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [16]:
ucs_420_Ayush=np.array([[10, 20, 30, 40],[50, 60, 70, 80], [90, 15, 20, 35]])

In [23]:
print(f"dimensions : {ucs_420_Ayush.ndim}")
print(f"mean: {ucs_420_Ayush.mean()}")
print(f"max:{ucs_420_Ayush.max()}")
print(f"min:{ucs_420_Ayush.min()}")
print(f"UNIque elements:{np.unique(ucs_420_Ayush)}")

dimensions : 2
mean: 43.333333333333336
max:90
min:10
UNIque elements:[10 15 20 30 35 40 50 60 70 80 90]


In [25]:
reshaped_ucs40_Ayush=np.reshape(ucs_420_Ayush,newshape=[4,3])
print(reshaped_ucs40_Ayush)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [27]:
resized_ucs_420=np.resize(ucs_420_Ayush,new_shape=[2,3])
print(resized_ucs_420)

[[10 20 30]
 [40 50 60]]


----------------------COMPLETEED-------------